name: "Hello world"


on: [push, pull_request]




jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: ./
      - run: npm ci
      - run: npm test

