name: "Hello World"

on: [push, pull_request]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Run the application
      run: node index.js
   
   

